apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-server
  namespace: sns
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: feed-server
  template:
    metadata:
      labels:
        app: feed-server
    spec:
      containers:
        - name: feed-container
          # ECR 주소 + tags
          image: 905418310587.dkr.ecr.ap-northeast-2.amazonaws.com/feed-server:0.0.1
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
          envFrom:
            - configMapRef:
                name: mysql-config
            - secretRef:
                name: mysql-secret
          resources:
            requests:
              memory: "512M"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          lifecycle:
            preStop:
              exec:
                # Rolling Update 로 파드가 교체될 때, update 가 느려지지만 안정적으로 교체될 수 있다는 장점
                command: ["/bin/sh", "-c", "sleep 10"]
          readinessProbe:
            httpGet:
              path: /healthcheck/ready
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthcheck/live
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 1
            failureThreshold: 7